version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: learnapp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
